name: BuildTraining
version: 1.0
main: me.kasper.BuildTraining
api-version: 1.12.2
authors: [kasperml]
commands:
  finish:
    usage: "/finish <10-100>"
    description: "Новое растояние"
  record:
    usage: "/record"
    description: "Лучшее время"